server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}/${TRAINING_DB_DATABASENAME}
    username: ${TRAINING_DB_USERNAME}
    password: ${TRAINING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none